### ISSUE TITLE
2 more steamers

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [razvan-flavius-panda/Clash-of-Code-Streamers#1]
Both english: saltAxAtlas, MirroredCat

**Comment by freeman42x** [comment]
@rozbrajaczpoziomow you can submit a PR if you want, otherwise I will add them later probably

**Comment by freeman42x** [comment]
Doen by @rozbrajaczpoziomow in https://github.com/razvan-flavius-panda/Clash-of-Code-Streamers/pull/2#pullrequestreview-600464659
